version: "3.9"
services:
  chronoscribe:
    build: .
    image: chronoscribe-agent:latest
    container_name: chronoscribe
    ports:
      - "9000:9000"
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","9000"]
    env_file:
      - .env
    environment:
      # Fallbacks if .env not present
      - OPENAI_MODEL=gpt-4o-mini
    restart: unless-stopped
